### ISSUE TITLE
Информация

### ISSUE THREAD

**Issue by linkinkov** [Ensemplix/Deobfuscator#1]
Можно в кратце объяснить как использовать это чудо?
Простая компиляция и запуск конечно же ничего не дает :)

**Comment by ensirius** [comment]
В данный момент программа только доделывается. Я старался максимально раздробить логику на разные компоненты и протестировать их. Это будет консольная утилита, в которую надо будет передать местоположение мода, который вы хотите декомпилировать.

**Comment by linkinkov** [comment]
Звучит великолепно, буду ждать краткую инфу по использованию, как будет готов. Спасибо!

**Comment by ensirius** [comment]
Сегодня закончу уже. Вы можете пока что изучить нашу библиотеку для команд. Она получилось очень интересной как мне кажется :)

**Comment by linkinkov** [comment]
А маппинги форга или mcp?

**Comment by ensirius** [comment]
Разве forge не берет маппинги из mcp?

**Comment by linkinkov** [comment]
Насколько я помню, различия есть.

**Comment by ensirius** [comment]
Так, релиза сегодня не будет. Завтра на свежую голову пересмотрю что понаписал

**Comment by linkinkov** [comment]
Удачи :+1:

**Comment by ensirius** [comment]
Все же добил :)

**Comment by linkinkov** [comment]
Можно показать пример параметров или пример декомпиляции? (правильной строки)

**Comment by ensirius** [comment]
Все просто до безумия:
```java
java -jar deobfuscator.jar mod.jar
```
```
Deobfuscating IndustrialCraft 2
Loaded 11494 mappings for 1.7.10 minecraft
Renaming fields and methods
Deobfuscated:
	field: 5409/5435
	method: 7075/7082
	param: 6/10
Decompiling:
```
